import Kernel
import Contract
import Compute
import Circuit

/// The **Driver** — the outer gateway ring that binds every device onto the kernel
/// bus (see the concentric architecture: dependencies point inward). It is the one
/// place the *convention* lives: which concrete backs each `@callable` port.
///
/// There is no hand-written per-device driver struct: the binding itself is already
/// generated by `@callable` (`Callable.<Layer>.<Device>.wire` emits one `register`
/// per protocol method, so none can be forgotten). This gateway just names the
/// concrete for each port — and takes every device as a parameter, so any impl can
/// be swapped by name (the pure devices default to their one impl; the
/// Infrastructure stores carry runtime dependencies and so are required).
///
/// A fully self-assembling wiring is impossible on purpose: macros can't enumerate
/// `@callable` types across modules and Swift structs have no runtime type
/// registry, so *some* manifest must name the bindings. This function is that
/// manifest — the minimal, single expression of the convention.
package func wireAllDrivers(
    into builder: KernelBuilder,
    slideshowStore: any LibraryStoring & SlideshowStoring,
    config: any ConfigStoring,
    slideshowCompute: any SlideshowComputing = SlideshowCompute(),
    imageCompute: any ImageComputing = ImageCompute(),
    libraryCircuit: any LibraryCircuiting = LibraryCircuit(),
    slideshowCircuit: any SlideshowCircuiting = SlideshowCircuit(),
    configCircuit: any ConfigCircuiting = ConfigCircuit()
) {
    // Infrastructure ports (leaf handlers → stores). One SwiftData actor backs both
    // slideshow ports: Library (catalog read) and Slideshow (per-slideshow CRUD).
    // Required parameters — the store carries its runtime (SwiftData) dependency.
    Callable.Infrastructure.Library.wire(slideshowStore, into: builder)
    Callable.Infrastructure.Slideshow.wire(slideshowStore, into: builder)
    Callable.Infrastructure.Config.wire(config, into: builder)
    // Compute ports (leaf handlers → pure business logic). Pure → defaulted, swappable.
    Callable.Compute.Slideshow.wire(slideshowCompute, into: builder)
    Callable.Compute.Image.wire(imageCompute, into: builder)
    // Circuit ports (composing handlers → orchestration that routes via the kernel).
    Callable.Circuit.Library.wire(libraryCircuit, into: builder)
    Callable.Circuit.Slideshow.wire(slideshowCircuit, into: builder)
    Callable.Circuit.Config.wire(configCircuit, into: builder)
}
